# Generated by Django 5.2.1 on 2025-05-21 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstrakPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_keluarga', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.BooleanField()),
                ('is_admin', models.BooleanField(default=False)),
                ('poin', models.IntegerField(db_column='poin', default=0)),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_keluarga', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('jumlah', models.FloatField()),
                ('satuan', models.CharField(max_length=50)),
                ('interval_habis', models.IntegerField()),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_keluarga', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('nominal', models.FloatField()),
                ('tanggal_transaksi', models.DateTimeField()),
                ('jenis', models.CharField(help_text='pemasukan atau pengeluaran', max_length=50)),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_keluarga', models.IntegerField()),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('tenggat_waktu', models.DateTimeField()),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('abstrakpengguna_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fo_app.abstrakpengguna')),
            ],
            bases=('fo_app.abstrakpengguna',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('abstrakpengguna_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fo_app.abstrakpengguna')),
            ],
            bases=('fo_app.abstrakpengguna',),
        ),
        migrations.CreateModel(
            name='PenggunaTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fo_app.abstrakpengguna')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fo_app.transaksikeuangan')),
            ],
        ),
        migrations.CreateModel(
            name='Penugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peran', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fo_app.abstrakpengguna')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fo_app.tugas')),
            ],
        ),
    ]
