# Generated by Django 5.2.1 on 2025-05-22 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_keluarga', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255)),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
