# Generated by Django 5.2.1 on 2025-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0002_tokenlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='poin',
            field=models.IntegerField(default=0),
        ),
    ]
