# Generated by Django 5.2.1 on 2025-05-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0003_tugas_poin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('belum_selesai', 'Belum Selesai'), ('selesai', 'Selesai')], default='belum_selesai', max_length=50),
        ),
    ]
