# Generated by Django 5.2.1 on 2025-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0004_alter_tugas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penugasan',
            name='peran',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], max_length=50),
        ),
    ]
