# Generated by Django 5.2.1 on 2025-05-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0005_alter_penugasan_peran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penugasan',
            old_name='user',
            new_name='pengguna',
        ),
        migrations.RenameField(
            model_name='penugasan',
            old_name='task',
            new_name='tugas',
        ),
    ]
