# Generated by Django 5.2.1 on 2025-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0006_rename_user_penugasan_pengguna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksikeuangan',
            name='jenis',
            field=models.CharField(choices=[('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], help_text='pemasukan atau pengeluaran', max_length=50),
        ),
    ]
