# Generated by Django 5.2.1 on 2025-05-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0007_alter_transaksikeuangan_jenis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penggunatransaksi',
            old_name='user',
            new_name='pengguna',
        ),
    ]
