# Generated by Django 5.2.1 on 2025-05-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0008_rename_user_penggunatransaksi_pengguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksikeuangan',
            name='pengguna',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_keuangan', to='fo_app.abstrakpengguna'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PenggunaTransaksi',
        ),
    ]
