# Generated by Django 5.2.1 on 2025-05-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0009_transaksikeuangan_pengguna_delete_penggunatransaksi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstrakpengguna',
            old_name='id_keluarga',
            new_name='_id_keluarga',
        ),
        migrations.RenameField(
            model_name='abstrakpengguna',
            old_name='password',
            new_name='_password',
        ),
        migrations.RenameField(
            model_name='stok',
            old_name='id_keluarga',
            new_name='_id_keluarga',
        ),
        migrations.RenameField(
            model_name='tokenlogin',
            old_name='id_keluarga',
            new_name='_id_keluarga',
        ),
        migrations.RenameField(
            model_name='tokenlogin',
            old_name='token',
            new_name='_token',
        ),
        migrations.RenameField(
            model_name='transaksikeuangan',
            old_name='id_keluarga',
            new_name='_id_keluarga',
        ),
        migrations.RenameField(
            model_name='tugas',
            old_name='id_keluarga',
            new_name='_id_keluarga',
        ),
    ]
