# Generated by Django 5.2.1 on 2025-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0010_rename_id_keluarga_abstrakpengguna__id_keluarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='terakhir_diingatkan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
