# Generated by Django 5.2.1 on 2025-06-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo_app', '0011_stok_terakhir_diingatkan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstrakpengguna',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
